### ISSUE TITLE
data pre-processing pipeline

### ISSUE THREAD

**Issue by Pang-Yatian** [sony/genwarp#10]
Dear authors,

Thanks for your great work.

Could you please share the details or scripts about data pre-processing? How do you run dust3r scripts to get depth and camera pose?

**Comment by j0seo** [comment]
Hi, @Pang-Yatian .  We used the z values of the pointmap for the first view as depth information. To obtain camera information, we used PnPRansac following: https://github.com/naver/dust3r/blob/c9e9336a6ba7c1f1873f9295852cea6dffaf770d/dust3r/cloud_opt/init_im_poses.py#L272

We have a preprocessing code, but it's not yet organized. If this is still okay with you, please email junyoung.seo@kaist.ac.kr, and I'll send it to you.

**Comment by Pang-Yatian** [comment]
Thanks a lot! I have sent you an email.
