### ISSUE TITLE
Error(s) in loading state_dict for ZoeDepth

### ISSUE THREAD

**Issue by micky-li-hd** [sony/genwarp#2]
RuntimeError: Error(s) in loading state_dict for ZoeDepth:
        Unexpected key(s) in state_dict: "core.core.pretrained.model.blocks.0.attn.relative_position_index", "core.core.pretrained.model.blocks.1.attn.relative_position_index", "core.core.pretrained.model.blocks.2.attn.relative_position_index", "core.core.pretrained.model.blocks.3.attn.relative_position_index", "core.core.pretrained.model.blocks.4.attn.relative_position_index", "core.core.pretrained.model.blocks.5.attn.relative_position_index", "core.core.pretrained.model.blocks.6.attn.relative_position_index", "core.core.pretrained.model.blocks.7.attn.relative_position_index", "core.core.pretrained.model.blocks.8.attn.relative_position_index", "core.core.pretrained.model.blocks.9.attn.relative_position_index", "core.core.pretrained.model.blocks.10.attn.relative_position_index", "core.core.pretrained.model.blocks.11.attn.relative_position_index", "core.core.pretrained.model.blocks.12.attn.relative_position_index", "core.core.pretrained.model.blocks.13.attn.relative_position_index", "core.core.pretrained.model.blocks.14.attn.relative_position_index", "core.core.pretrained.model.blocks.15.attn.relative_position_index", "core.core.pretrained.model.blocks.16.attn.relative_position_index", "core.core.pretrained.model.blocks.17.attn.relative_position_index", "core.core.pretrained.model.blocks.18.attn.relative_position_index", "core.core.pretrained.model.blocks.19.attn.relative_position_index", "core.core.pretrained.model.blocks.20.attn.relative_position_index", "core.core.pretrained.model.blocks.21.attn.relative_position_index", "core.core.pretrained.model.blocks.22.attn.relative_position_index", "core.core.pretrained.model.blocks.23.attn.relative_position_index". 
       
       i meet the problem that https://github.com/isl-org/ZoeDepth/releases/download/v1.0/ZoeD_M12_N.pt can't be used for zoedepth/zoedepth_v1.py

**Comment by kaz-sony** [comment]
Hi @LiHaodong0217 , Could you tell us more about how you got this error, such as environments and commands to reproduce it? Thank you.

**Comment by Linusnie** [comment]
@LiHaodong0217 I had this issue as well, solved with `run pip install timm==0.6.7` [https://github.com/isl-org/ZoeDepth/issues/97#issuecomment-2041500556](https://github.com/isl-org/ZoeDepth/issues/97#issuecomment-1872221873)

**Comment by kaz-sony** [comment]
Thank you @Linusnie for your help. As stated in readme, it is needed to install requirements_dev.txt to run notebooks and demos. The package timm is included in requirements_dev.txt.

@LiHaodong0217 Could you check if it works for you and report back to us?

**Comment by kaz-sony** [comment]
Closing the issue as we have got no response. Feel free to reopen it if the problem persists. Thank you.
