### ISSUE TITLE
problem about online demo

### ISSUE THREAD

**Issue by micky-li-hd** [sony/genwarp#4]
Can we use multi-view images to test？
![image](https://github.com/user-attachments/assets/fbfd33a0-fc85-4ad9-a11d-59676135fc78)

as you can see，it isn't really work

**Comment by kaz-sony** [comment]
Hi @LiHaodong0217 , What do you mean by multi-view images? If you mean the number of images larger than one, our model takes only a single image as input as stated in the title. If you are not satisfied with the result of current output like your example above, please try smaller camera movement first. Our model is not trained with such a large displacement of the camera. Instead, you can try to progressively generate small camera movements by using the previous output as a new input like a feedback loop, repeating until you get your desired camera position. This may not result in the best quality but we think it might be better than the one-step generation. This is also stated in our spaces page. So please do check it out.

**Comment by kaz-sony** [comment]
Closing the issue as we haven't heard from the opener for further clarifications. Feel free to reopen it if anybody has anything to add.
