### ISSUE TITLE
When I run "python app.py"， an error occurs:

### ISSUE THREAD

**Issue by Sampkao** [sony/genwarp#5]
When I run "python app.py"， an error occurs:
***
Traceback (most recent call last):
  File "D:\Temp\SDWebui\genwarp\app.py", line 19, in <module>
    from genwarp import GenWarp
  File "D:\Temp\SDWebui\genwarp\genwarp\__init__.py", line 1, in <module>
    from .GenWarp import GenWarp
  File "D:\Temp\SDWebui\genwarp\genwarp\GenWarp.py", line 24, in <module>
    from .ops import get_viewport_matrix, forward_warper
  File "D:\Temp\SDWebui\genwarp\genwarp\ops.py", line 10, in <module>
    from splatting import splatting_function
  File "D:\ProgramData\anaconda3\envs\sdwebui\lib\site-packages\splatting\__init__.py", line 1, in <module>
    from .splatting import Splatting, splatting_function, SummationSplattingFunction
  File "D:\ProgramData\anaconda3\envs\sdwebui\lib\site-packages\splatting\splatting.py", line 6, in <module>
    from splatting import cpu as splatting_cpu
ImportError: DLL load failed while importing cpu: The specified program cannot be found.
***
could you help me to check this? Thanks.

**Comment by kaz-sony** [comment]
Hi @Sampkao , Thank you for your trial. It looks like you're on a Windows machine without a GPU. Although it could be possible to run the model on such kind of machines, we'are sorry that we didn't test our codes on and will not support it. We'll add lines about supported machines in the readme soon.

It seems that it is the problem of installing [splatting package](https://github.com/pesser/splatting) rather than our codes on the repository. Hence I'm closing this issue. Please feel free to open a new issue if you find any bugs in this repository. Thank you.

**Comment by kaz-sony** [comment]
As a side note, you can try Docker to virtually recreate a linux environment as mentioned in the [readme](https://github.com/pesser/splatting) or you can try it out on our [Spaces](https://huggingface.co/spaces/Sony/genwarp) without bothering you too much if you just want to get your hands on it.

**Comment by Sampkao** [comment]
My device uses a RTX GPU with 12GB Vram, but the version of pytorch I installed is as follows:
torch==2.0.1+cu118 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

If I use the default installation version, the following error will occur:
"Can not find CUDA..."
It seems that the CUDA 11.8 version in my system is not compatible with that pytorch version?

BTW, I've used the trial you provided and love it that I wanted to try it locally. I'm not familiar with Docker, I'll do some research.

**Comment by kaz-sony** [comment]
Did you install CUDA toolkit on your system? It seems your system couldn't find it. It requires CUDA to run the model in both cases with and without Docker. Besides, your GPU may not be sufficient to load our model. In our experiment, it used up around 15GB of VRAM. Many models out there tend to require different setups specific to them. I generally recommend using Docker to separate problems.

We're happy to hear that you enjoyed our demo! Thank you.

**Comment by Sampkao** [comment]
I see, it may indeed be a problem with my cuda toolkit. This part was modified when I installed other packages a while ago. I will confirm again. 

Your work is indeed very helpful for my use cases (animations and comics). I will try the Docker or website method and hope for more quantitative results from you in the future :)
